/**
 * Builder-owned page documents + deterministic React codegen.
 *
 * A page lives as JSON under <fixture>/pages/<name>.json. Saving regenerates
 * <fixture>/src/pages-gen/<name>.tsx — clean, readable JSX that the harness
 * imports and renders directly. What the canvas shows IS the generated code.
 *
 * Every section/column/block carries data-uai-block="<id>" so the canvas can
 * map DOM clicks back to document nodes without any parsing.
 */
import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Document model
// ---------------------------------------------------------------------------

export interface PageDoc {
  name: string;
  title: string;
  sections: Section[];
}

export interface Section {
  id: string;
  /** Visual treatment straight from the fixture design system. */
  background: "none" | "card" | "well";
  padding: string;
  gap: string;
  columns: Column[];
}

export interface Column {
  id: string;
  /** flex-grow weight; "1" is an equal column. */
  flex: string;
  gap: string;
  blocks: Block[];
}

export type Block =
  | { id: string; type: "heading"; level: 1 | 2 | 3; text: string }
  | { id: string; type: "text"; text: string }
  | { id: string; type: "button"; label: string }
  | { id: string; type: "image"; src: string; alt: string; width: string }
  | { id: string; type: "spacer"; height: string }
  | {
      id: string;
      type: "component";
      file: string;
      exportName: string;
      props: Record<string, unknown>;
    };

// ---------------------------------------------------------------------------
// Codegen
// ---------------------------------------------------------------------------

const IND = "  ";

function jsxText(text: string): string {
  return /^[^{}<>&"']*$/.test(text) ? text : `{${JSON.stringify(text)}}`;
}

/** JSON is valid JS — pretty-print prop objects as object literals. */
function propsLiteral(props: Record<string, unknown>, indent: string): string {
  const json = JSON.stringify(props, null, 2);
  return json.split("\n").join(`\n${indent}`);
}

function componentImportPath(file: string): string {
  // fixtures/demo-project/src/components/... → ../components/... (from pages-gen/)
  const marker = "/src/";
  const i = file.indexOf(marker);
  return "../" + file.slice(i + marker.length).replace(/\.tsx?$/, "");
}

const SECTION_BG: Record<Section["background"], string> = {
  none: "",
  card: "ui-card",
  well: "ui-iconwell--recess",
};

function genBlock(block: Block, d: string): string {
  const tag = `data-uai-block="${block.id}"`;
  switch (block.type) {
    case "heading": {
      const h = `h${block.level}`;
      return `${d}<${h} ${tag} style={{ margin: 0 }}>${jsxText(block.text)}</${h}>`;
    }
    case "text":
      return `${d}<p ${tag} style={{ margin: 0 }}>${jsxText(block.text)}</p>`;
    case "button":
      return `${d}<button ${tag} type="button" className="ui-card" style={{ padding: "0.5rem 1.25rem", cursor: "pointer", font: "inherit", border: "none" }}>${jsxText(block.label)}</button>`;
    case "image":
      return `${d}<img ${tag} src=${JSON.stringify(block.src)} alt=${JSON.stringify(block.alt)} style={{ width: ${JSON.stringify(block.width)}, maxWidth: "100%" }} />`;
    case "spacer":
      return `${d}<div ${tag} style={{ height: ${JSON.stringify(block.height)} }} />`;
    case "component":
      throw new Error("component blocks are emitted inline by generatePage");
  }
}

export function generatePage(doc: PageDoc): string {
  // Collect component imports (deduped by export name).
  const imports = new Map<string, string>();
  for (const s of doc.sections)
    for (const c of s.columns)
      for (const blk of c.blocks)
        if (blk.type === "component")
          imports.set(blk.exportName, componentImportPath(blk.file));

  const lines: string[] = [];
  lines.push("// Generated by u-and-i — edit in the visual builder.");
  lines.push(`// Source document: pages/${doc.name}.json`);
  for (const [name, from] of imports)
    lines.push(`import { ${name} } from "${from}";`);
  if (imports.size) lines.push("");
  lines.push(`export default function Page() {`);
  lines.push(`${IND}return (`);
  lines.push(
    `${IND.repeat(2)}<main style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>`,
  );

  for (const s of doc.sections) {
    const cls = SECTION_BG[s.background];
    const clsAttr = cls ? ` className="${cls}"` : "";
    const d3 = IND.repeat(3);
    lines.push(
      `${d3}<section data-uai-block="${s.id}"${clsAttr} style={{ padding: ${JSON.stringify(s.padding)} }}>`,
    );
    lines.push(
      `${d3}${IND}<div style={{ display: "flex", gap: ${JSON.stringify(s.gap)}, alignItems: "flex-start" }}>`,
    );
    for (const c of s.columns) {
      const d5 = IND.repeat(5);
      lines.push(
        `${d5}<div data-uai-block="${c.id}" style={{ flex: ${JSON.stringify(c.flex)}, display: "flex", flexDirection: "column", gap: ${JSON.stringify(c.gap)}, minWidth: 0 }}>`,
      );
      for (const blk of c.blocks) {
        if (blk.type === "component") {
          const d6 = IND.repeat(6);
          lines.push(`${d6}<div data-uai-block="${blk.id}">`);
          lines.push(
            `${d6}${IND}<${blk.exportName} {...${propsLiteral(blk.props, d6 + IND)}} />`,
          );
          lines.push(`${d6}</div>`);
        } else {
          lines.push(genBlock(blk, IND.repeat(6)));
        }
      }
      lines.push(`${d5}</div>`);
    }
    lines.push(`${d3}${IND}</div>`);
    lines.push(`${d3}</section>`);
  }

  lines.push(`${IND.repeat(2)}</main>`);
  lines.push(`${IND});`);
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

export function pagesDir(fixtureRoot: string): string {
  return path.join(fixtureRoot, "pages");
}

export function genDir(fixtureRoot: string): string {
  return path.join(fixtureRoot, "src", "pages-gen");
}

export function listPages(fixtureRoot: string): string[] {
  const dir = pagesDir(fixtureRoot);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}

export function loadPage(fixtureRoot: string, name: string): PageDoc {
  const file = path.join(pagesDir(fixtureRoot), `${name}.json`);
  return JSON.parse(fs.readFileSync(file, "utf8")) as PageDoc;
}

/** Save the document and regenerate its page module atomically-enough. */
export function savePage(fixtureRoot: string, doc: PageDoc): void {
  if (!/^[\w-]+$/.test(doc.name)) throw new Error("bad page name");
  fs.mkdirSync(pagesDir(fixtureRoot), { recursive: true });
  fs.mkdirSync(genDir(fixtureRoot), { recursive: true });
  fs.writeFileSync(
    path.join(pagesDir(fixtureRoot), `${doc.name}.json`),
    JSON.stringify(doc, null, 2) + "\n",
    "utf8",
  );
  fs.writeFileSync(
    path.join(genDir(fixtureRoot), `${doc.name}.tsx`),
    generatePage(doc),
    "utf8",
  );
}
